### ISSUE TITLE
startController classname

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1843] opened 2017-10-13 17:49 UTC
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/startController.js#L73 - expects a selector rather than a classname, so we may wish to either amend the `_className` attribute to make this clearer or amend the method to look at classes specifically.

**Comment by NayanKhedkar** [comment] 2017-11-08 07:08
PR:https://github.com/adaptlearning/adapt_framework/pull/1858

**Comment by NayanKhedkar** [comment] 2017-11-09 09:44
@danielghost  could you please elaborate more?

**Comment by oliverfoster** [comment] 2017-11-10 16:45
http://api.jquery.com/is/ uses a css selector ``tagName.className#id[name=value]`` the attribute is called ``_className`` even though it's not just a class name, it's a selector.
@danielghost is making a point about the clarity of the variable name because he and I struggled to set it up correctly without reading the code.

**Comment by NayanKhedkar** [comment] 2017-11-13 09:06
Here we provided _className with dot(.) prefix **i.e**. "_className": ".size-small.touch, .size-medium.touch".
So we can not go for `$html.hasClass(className)` and also we can't provide multiple classes to hasClass().need to be change documentation also.
What would you prefer @oliverfoster ?

**Comment by oliverfoster** [comment] 2017-11-13 09:13
``hasClass`` doesn't allow for and/or style rules.
So you can't do ``.size-small.touch, .size-medium.touch`` which is ``(size-small && touch) || (size-medium && touch)``.
I like Tom's suggestion in that it allows the expected behaviour for "className" as well as allowing selectors, with one variable. It make sense because it's simple and satisfies all the requirements with the minimal amount of effort.
```javascript
var $html = $("html");

if (!className || $html.is(className) || $html.hasClass(className)) {
```

**Comment by NayanKhedkar** [comment] 2017-11-13 09:42
Ok that's fine @oliverfoster

**Comment by NayanKhedkar** [comment] 2017-11-13 09:46
PR:https://github.com/adaptlearning/adapt_framework/pull/1865

**Comment by sarveshwar-gavhane** [comment] 2017-11-13 12:58
can some one close this issue ?

**Comment by oliverfoster** [comment] 2017-11-13 12:58
👍

**Closed** 2017-11-13 12:58 UTC
