### ISSUE TITLE
IE8 and The "jump to top" scrolling issue

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#899] opened 2016-01-13 07:14 UTC
This is general to the framework but I could replicate it on the page with the media component. I was clicking on open transcript button. I've checked this on the 2.0.6 version, page co-05.

**Comment by moloko** [comment] 2016-06-06 10:42
@LukaszGrela is this still happening?

**Comment by sarveshwar-gavhane** [comment] 2016-07-05 06:25
@moloko  i have tested on IE8, this is not happening, this issue can be closed.....???

**Comment by LukaszGrela** [comment] 2016-07-05 07:23
Yes it is still hapenning, IE8 (8.0.6001.18702IC) on Win XP - here you can see the scrollbar moving up and down), on Win 7 IE11 in emulation of IE8 (here you can see the flash of the content from above).
If other can't replicate then maybe it is something peculiar to my machine?

**Comment by chris-steele** [comment] 2016-08-23 10:28
@LukaszGrela just to note, support for IE8 on XP has been dropped, so this issue is unlikely to resolved any time soon.

**Comment by andrewhosgood** [comment] 2016-08-25 09:54
Also, I don't know how reliable an emulation of IE8 would be and whether to trust it or not...

**Comment by LukaszGrela** [comment] 2016-09-02 06:57
I know guys, also emulation was used as a quick reference for those who can't get the real IE8 (curses). The IE8 itself is also (still) used as an embedded control in applications like Saba Anywhere (where on the other hand it is recognised as IE7 by Adapt).

**Comment by moloko** [comment] 2016-11-28 15:08
duplicate of #900

**Closed by moloko** 2016-11-28 15:08 UTC
