### ISSUE TITLE
adapt-contrib-narrative: first pin of hotgraphic remains visited on resizing 

### ISSUE THREAD

**Issue by chetan-hajare** [adaptlearning/adapt_framework#2483] opened 2019-07-29 09:28 UTC
### Subject of the issue/enhancement/features
There are two issues related to conversion from narrative to hotgraphic.
1. The first pin gets marked as visited while converting from mobile view to desktop view even if the narrative on mobile device is not viewed.
2. A page having two or more hotgraphic when resized to small and back to desktop, the number of hotgraphic gets increased.

### Your environment
* version (AT/Framework) -  4.2.0
* which browser and its version - All major browsers
* device(s) + operating system(s) - Windows 10

### Steps to reproduce
Issue 1 -
- Run the latest framework on desktop.
- Resize the browser window to small and then again to desktop view.
- The first pin of hotgraphic is marked as visited.

Issue 2 -
- Add two instances of hotgraphic on the same page.
- Resize the browser window to small and then again to desktop view.
- Other than first hotgraphic, there will be two instances of second hotgraphic component.
- Again resizing the browser window to small and then again to desktop view.
- There will be two instances of first hotgraphic and eleven instances of second one.

### Expected behaviour
1 - The first pin of hotgraphic should remain unvisited until actually visited.
2 - The number of instances of hotgraphic component should not change on resizing the window.

**Comment by tomgreenfield** [comment] 2019-07-29 09:38
Second part is a duplicate of #2435.

**Comment by chetan-hajare** [comment] 2019-07-29 09:43
> Second part is a duplicate of #2435.

Thanks for notifying. Updating subject to handle first issue.

**Comment by guywillis** [comment] 2020-10-22 09:12
I believe this issue is now resolved via this PR - https://github.com/adaptlearning/adapt_framework/pull/2949

Related issue: https://github.com/adaptlearning/adapt_framework/issues/2938

**Closed by guywillis** 2020-10-22 09:12 UTC
