### ISSUE TITLE
Slider - Setting _showScaleIndicator to false does not hide the indicators

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#864] opened 2016-01-04 14:36 UTC
_From @brian-learningpool on November 6, 2015 13:33_

I would expect this to hide the indicators, when this is set to `false`.  It doesn't seem to do that.

_Copied from original issue: adaptlearning/adapt-contrib-slider#88_

**Comment by guywillis** [comment] 2016-01-04 14:36
_From @moloko on November 6, 2015 14:52_

this works OK for me... this is with it set to `true`:
![slider_showscaleindicator-true](https://cloud.githubusercontent.com/assets/1249597/10999801/f756c73e-8495-11e5-9a0f-8a5486aa4fda.png)
and this is with it set to `false`:
![slider_showscaleindicator-false](https://cloud.githubusercontent.com/assets/1249597/10999809/02597352-8496-11e5-9254-c039281c1f96.png)
Which matches the behaviour that's documented in the README:
> _showScaleIndicator (boolean): When set to true, a marker for the position of the slider along the scale is shown. If _showNumber is true this marker will contain a numeric value. If _showNumber is false a blank marker is shown.

**Comment by brian-learningpool** [comment] 2016-02-29 09:34
Closing ticket as this is by design.

**Closed by brian-learningpool** 2016-02-29 09:34 UTC
Labels: bug
