### ISSUE TITLE
adapt-contrib-assessment: Inconsistent behaviour between assessment and question weighting during score calculation

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_framework#2510] opened 2019-08-21 15:51 UTC
### Subject of the issue/enhancement/features
Assessment and question weightings appear to be applied differently.
Setting a question weighting of >1 increases the question's overall score contribution to the assessment. In contrast, setting an assessment weighting of >1 decreases the assessment's overall contribution.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
1. Create a new course. Add the following extensions: Assessment, and Spoor.
1. Navigate to "Configuration Settings". Under "Extensions" -> "Spoor", set "Is Enabled", and SCORM debug window to True.
1. Create a page with 2 questions. 
1. For question 1, set the question weighting to 1. For question 2, set the weighting to 4.
1. Navigate to the article settings where the 2 question components reside in. 
1. In the article settings, under "Extensions" -> "Assessment", set "Enabled" and "Include in Total Score" to True. 
1. Type in assess02 into "Assessment ID", and set the "Assessment Weight" to 1. Click Save.
1. Copy and paste the article. Navigate into the article properties of the pasted article.
1. Change the assessment ID of the pasted article to "assess02". Change the assessment weighting to 4.
1. Click Save. Click Preview.
1. On the preview tab, bring up the browser developer tool (press F12). 
1. On the browser developer tool, open the “Console” tab.
1. Navigate to assessment 01. Correctly answer question 01, fail question 02.
1. Navigate to assessment 02. Fail all questions.
1. On the browser developer tool, look for entries titled “*SCORM.data.set('cmi.core.score.raw)*”. Notice that “*value*” is 16 instead of 4. Question 01 from assessment 01 should have the lowest overall score contribution.

### Expected behaviour
A question with a high question weighting from an assessment with a high assessment weighting should result in the question contributing more to the overall score. Conversely, a low question and assessment weighting pairing should result in a smaller overall score contribution.

### Actual behaviour
Assessment weighting appears to be inversely applied to the overall score. See supplied screenshot.

### Screenshots (if you can)
![screenshot 2019-08-21 (1)](https://user-images.githubusercontent.com/48051681/63447212-8bd6d800-c433-11e9-9cf9-b5b0dbb29fa9.jpg)

**Comment by moloko** [comment] 2019-08-23 13:54
> In contrast, setting an assessment weighting of >1 decreases the assessment's overall contribution

This is actually as-designed - as the help text for Assessment Weight states, "If there are multiple assessments in the course, this value controls the proportion of the LMS score which is attributed to this assessment, i.e. 1 equals 100%, 0.5 is 50%, etc."

**Comment by canstudios-kent** [comment] 2019-08-28 08:29
> > In contrast, setting an assessment weighting of >1 decreases the assessment's overall contribution
> 
> This is actually as-designed - as the help text for Assessment Weight states, "If there are multiple assessments in the course, this value controls the proportion of the LMS score which is attributed to this assessment, i.e. 1 equals 100%, 0.5 is 50%, etc."

Does this mean an assessment weighting of 2 should intentionally equal 50% instead of the 200% as I had originally thought?

**Comment by moloko** [comment] 2019-08-28 09:39
Yes, exactly. See [these two lines of code](https://github.com/adaptlearning/adapt-contrib-assessment/blob/9aefd2142aa4b7601950725d684c3d96575397c5/js/assessment.js#L365-L366).

**Comment by kevindoherty30** [comment] 2019-09-02 16:08
I've actually noticed this as well, and maybe I'm misunderstanding this but if I have two assessments, each with 10 questions, I set the assessment weight to 0.5 for each of them, I get 5 questions correct on each assessment and instead of achieving a score of 10/20 then I receive a score of 20/40, is that by design?

should I be setting the assessment weight on the two assessments to 2 in order to achieve the 10/20 score?

Was there not previously a requirement that the assessment weight for all assessments add up to 1?

**Comment by canstudios-kent** [comment] 2019-09-05 09:23
The lack of help text for the question weightings also adds to the confusion. The wuestion weighting is applied to the scoring in the way that is described in the Assessment Weighting's help text (value greater than 1 increases score contribution; value between 0 and 1 decreases score contribution).
Wouldn't it be more intuitive for the user if the assessment weights were applied as a multiplier instead of a divisor? It would also make the current help text be accurate.

**Comment by oliverfoster** [comment] 2019-09-05 09:31
> Wouldn't it be more intuitive for the user if the assessment weights were applied as a multiplier instead of a divisor? It would also make the current help text be accurate.

Most changes to question marking will likely generate a large amount of work which isn't backward compatible. All core and third party question components would probably need changes along with updates to the framework. 
There is a parallel conversation happening [here](https://github.com/adaptlearning/adapt_framework/issues/2515#issuecomment-527854950) about something similar.

**Comment by canstudios-kent** [comment] 2019-09-06 09:31
>There is a parallel conversation happening on #2515 about something similar. Can I suggest that if we go for changes to question marking that we go for the whole hog whilst we're there?
After reading the discussion on #2515, I am happy for #2510 to be sorted with #2515.

**Comment by oliverfoster** [comment] 2021-05-12 08:57
part of #1974

**Comment by oliverfoster** [comment] 2021-09-13 08:36
closed in favour of #2515

**Closed by oliverfoster** 2021-09-13 08:36 UTC
Labels: enhancement
