### ISSUE TITLE
Media Component: preventForwardScrubbing bypass method

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt_framework#2237] opened 2018-09-27 14:22 UTC
### Subject of the issue/enhancement/features
With preventForwardScrubbing enabled, users may bypass by double-clicking at a future section of the timeline

### Your environment
* Adapt Framework
* Internet Explorer v11 & Microsoft Edge
* Windows 10

### Steps to reproduce
Enable preventForwardScrubbing, open IE or Edge, and double-click at a future part of the video scrub bar.

### Expected behaviour
Ideally, like in Chrome and Firefox, this should function the same.

### Actual behaviour
Users my bypass the locking mechanism and explore further areas of the video.

### Screenshots (if you can)
Not relevant!

**Comment by moloko** [comment] 2018-09-27 15:20
duplicate of #1681

not really sure what we can about this, when the feature was added we were aware it wouldn't always work - which is why the docs say "will _attempt_ to prevent users from skipping ahead in media"

**Closed by moloko** 2018-09-27 15:20 UTC
Labels: duplicate
