### ISSUE TITLE
Hotgraphic - Tabbing loses focus in item popup

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#851] opened 2016-01-04 14:18 UTC
_From @RobertPeek on November 27, 2015 14:40_

When tabbing through the default adapt build, the focus is lost when tabbing reaches the final text field in a hotgraphic's item popup. The focus returns to the top of the page, then to the instruction text on the narrative compoennt, and then finally on to the close button within the hotgraphic popup.

_Copied from original issue: adaptlearning/adapt-contrib-hotgraphic#120_

**Comment by moloko** [comment] 2016-02-08 11:36
duplicate of #908

**Comment by moloko** [comment] 2016-02-15 21:09
should be fixed by adaptlearning/adapt-contrib-narrative/pull/156

**Closed by moloko** 2016-02-15 21:09 UTC
