### ISSUE TITLE
Loading issue on Chrome brower on Android.

### ISSUE THREAD

**Issue by riveneo** [adaptlearning/adapt_framework#3131] opened 2021-04-21 10:36 UTC
### Subject of the issue/enhancement/features
We're experiencing loading issues on Chrome browser on Android mobile devices specifically. The courses work properly on Apple mobile devices, on Firefox on Android mobile devices and on PC/Notebook. Just the Chrome/Android combination is not working. We've tested this on multiple different devices.

### Your environment
* 4.0.1
* Chrome 90.0.4430.66
* Various Mobile Phones - Android

### Steps to reproduce
Open a course in Chrome on a mobile Android device.

### Expected behaviour
When the page is done loading, the content should display.

### Actual behaviour
The page's loading icon does not disappear. Removing it with devtools does not show any content either. Devtools does not give any javascript errors.

**Comment by tomgreenfield** [comment] 2021-04-21 10:40
Could this be a duplicate of https://github.com/adaptlearning/adapt_framework/issues/2734?

If so, you can try installing this [plugin](https://github.com/cgkineo/adapt-lazyLoadPatch).

**Comment by oliverfoster** [comment] 2021-04-26 10:52
@riveneo Is this working for you now?

**Comment by riveneo** [comment] 2021-04-26 10:55
@oliverfoster @tomgreenfield ,

Yes, we've managed to get the course working again.

Thank you very much!

**Closed** 2021-04-26 11:04 UTC
Labels: awaiting response
