### ISSUE TITLE
issue in MCQ

### ISSUE THREAD

**Issue by rakeshkumar749** [adaptlearning/adapt_framework#2980] opened 2020-12-01 04:48 UTC
### Subject of the issue/enhancement/features
Describe your issue here.

### Your environment
Authoring Tool Version: 0.10.5
Framework Version: 5.7.1
Node.js Version: 12.17.0
MongoDB Version:6.14.4
Operating System: windows 10
Browser: Chrome, Edge, Firefox

### Steps to reproduce
1. attempt MCQ/MMCQ and go to menu or other page
2. come back on page where MCQ/MMCQ already attempted
3. Not able to check "My Answer" and "Correct Answer" buttons.

### Expected behaviour
on revisit, the "Correct Answer" buttons should be active on MCQ/MMCQ. if MCQ is "False" on drop down for revisit.

### Actual behaviour
on revisit the mcq/mmcq, "Correct Answer" button is not active.

**Comment by moloko** [comment] 2020-12-03 15:16
@rakeshkumar749 if you change all instances of `"_isResetOnRevisit": "false"` to `"_isResetOnRevisit": false` in components.json in the published version of your course, does that fix this issue for you? 

If so, this is a duplicate of #2825

**Comment by rakeshkumar749** [comment] 2020-12-03 15:28
yes that is fix the problem.

**Closed** 2020-12-03 17:44 UTC
Labels: duplicate
