### ISSUE TITLE
Narrative - RTL tabbing issue

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#861] opened 2016-01-04 14:27 UTC
_From @RobertPeek on November 27, 2015 14:56_

When the default adapt framework is viewed in RTL, tabbing through the Narrative component causes issues with the forward and back arrows. When tabbing to the first forward button, the button reverts back to the side it would have been in LTR.

_Copied from original issue: adaptlearning/adapt-contrib-narrative#153_

**Comment by moloko** [comment] 2016-02-08 11:34
duplicate of #909

**Closed by moloko** 2016-02-08 11:34 UTC
