### ISSUE TITLE
Spoor schema throws errors

### ISSUE THREAD

**Issue by ptabak** [adaptlearning/adapt_framework#3344] opened 2022-12-01 14:05 UTC
Trying to build a newly created course with `grunt build` throws the following warning which results in the task aborting prematurely:

`Running "schema-defaults" task`   
`Warning: src/extensions/adapt-contrib-spoor/properties.schema: Unexpected token c in JSON at position 12082 Use --force to continue.`

Replacing default adapt-contrib-spoor extension with v5.2.1 fixes the issue.

### Your environment
* Adapt Framework v5.22.11
* macOS 12.4
* node v14.21.1

### Steps to reproduce
Create a new course with `adapt create course`
Switch to newly created course directory and run `grunt build`

### Expected behaviour
Course should build successfully

### Actual behaviour
Grunt build task aborts due to warnings

**Comment by NotMyself** [comment] 2022-12-06 21:11
This is the root cause of the build issue described in adaptlearning/adapt-cli#181

This issue currently has all our builds broken. Is there specific guidance on how to avoid these kinds of version issues in dependent projects?

**Comment by chris-steele** [comment] 2023-01-04 11:46
Good spot and thank you. Will be fixed by https://github.com/adaptlearning/adapt_framework/pull/3352

**Comment by oliverfoster** [comment] 2023-01-16 11:38
Fixed

**Closed by oliverfoster** 2023-01-16 11:38 UTC
