### ISSUE TITLE
Class of "submitted" not added to incorrectly answered MCQ and GMCQ

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt_framework#1089] opened 2016-06-06 15:13 UTC
Pretty sure this is related to https://github.com/adaptlearning/adapt_framework/issues/921, but when answering an MCQ (or GMCQ), the class of `submitted` is not added to the `.component-widget` when you submit an incorrect answer.

Clicking "Show Answer" will add the missing class in.

Used to be: https://github.com/adaptlearning/adapt_framework/blob/v2.0.9/src/core/js/views/questionView.js#L220

Now: https://github.com/adaptlearning/adapt_framework/blame/v2.0.10/src/core/js/views/questionView.js#L148

**Comment by andrewhosgood** [comment] 2016-06-06 15:22
...of course I'm speculating entirely where the actual issue lies

**Comment by moloko** [comment] 2016-06-06 15:34
if we go ahead with something similar to what is proposed in #921, that would certainly help prevent this kind of issue from happening but otherwise I don't see how it would be related?

**Comment by andrewhosgood** [comment] 2016-06-06 15:39
Sorry, that's what I meant - there's some disparity between the model and the view which will be solved by #921.

When you submit the answer, it used to show marking on the item options, styled by the class of `submitted`. Someone pointed out to me the other day that it no longer does that.

**Comment by tomgreenfield** [comment] 2016-06-28 14:33
Duplicate of #1114?

**Comment by andrewhosgood** [comment] 2016-06-29 09:58
Yes, or rather #1114 is a duplicate of this :smirk:

**Comment by tomgreenfield** [comment] 2016-07-12 15:57
Done in bb2396f.

**Closed by tomgreenfield** 2016-07-12 15:57 UTC
