### ISSUE TITLE
Narrative component - you can see the next image slightly

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3032] opened 2021-02-11 12:45 UTC
### Subject of the issue/enhancement/features
White line appearing below image and text as you are able to see the next image slightly. See the attached screenshot.

### Your environment
IE11

### Steps to reproduce
Add a narrative component with 6 items and view this in IE11. 

### Expected behaviour
You should not be able to see the next image.

### Actual behaviour
You can see the next image.

### Screenshots (if you can)
<img width="730" alt="Screenshot 2021-02-10 at 10 46 48" src="https://user-images.githubusercontent.com/61159216/107638010-e6d33f00-6c66-11eb-87ea-64679a70d8a6.png">

**Comment by oliverfoster** [comment] 2021-02-11 12:53
I think there is no easy mathematical solution to this problem with CSS as IE11 does some fun things with subpixel rendering especially around fractions with truncated decimals that don't round evenly to one. Like 3*(1/3) = 0.9999999999 in CSS giving a lovely subpixel problem handled badly by the renderer.

It might be an idea to just hide the other slides on transitionend and show them again on slide movement?

**Comment by eleanor-heath** [comment] 2021-02-11 12:56
> I think there is no easy mathematical solution to this problem with CSS as IE11 does some fun things with subpixel rendering especially around fractions with truncated decimals that don't round evenly to one. Like 3*(1/3) = 0.9999999999 in CSS giving a lovely subpixel problem handled badly by the renderer.
> 
> It might be an idea to just hide the other slides on transitionend and show them again on slide movement?

I have a solution for this if you could take a look please https://github.com/adaptlearning/adapt-contrib-narrative/pull/208

**Comment by moloko** [comment] 2021-02-11 14:43
duplicate of #2620 (or at least very similar)

**Comment by oliverfoster** [comment] 2021-05-12 09:46
closing comment with potential solution https://github.com/adaptlearning/adapt-contrib-narrative/pull/209#issuecomment-826797537

**Closed** 2021-05-24 23:15 UTC
Labels: wontfix
