### ISSUE TITLE
add option to view glossary & resources seperatly 

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#2221] opened 2018-08-30 11:50 UTC
### enhancement/features
add option to view glossary & resources seperatly with different icons.

### Steps to reproduce
enabled glossary extension with resource 

### Expected behaviour
currently we can view both extension elements in same drawer view,but when you have many elements in each extension, it turns to be confusing to go back and view other extension element. 
 
### Screenshots (if you can)
![example](https://user-images.githubusercontent.com/12641875/44849395-97a41a00-ac77-11e8-90c0-524218e97ab9.jpg)

**Comment by ODHORACANVAS** [comment] 2018-08-31 20:26
odhora canvas house idea
![2015-11-07 00 28 10-19](https://user-images.githubusercontent.com/11202474/44934385-8dc1fb80-acf7-11e8-9c83-2cc8b15d6c05.jpg)

**Comment by akshay-bhavsar** [comment] 2018-09-03 11:57
you mean to say,
there will be different icon for glossary other than drawer icon?

**Comment by moloko** [comment] 2018-12-17 16:52
I think this might be a duplicate of #1378 ?

**Comment by sarveshwar-gavhane** [comment] 2019-04-02 11:47
yes it is..

**Closed** 2019-04-02 13:09 UTC
Labels: duplicate, feature request
