### ISSUE TITLE
xAPI not restoring users language selection when resuming a course

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#3011] opened 2021-01-11 11:36 UTC
### Subject of the issue/enhancement/features
When viewing a multi-language course with xAPI enabled, the users selected language is not being restored when they revisit the course. Instead the user is prompted to select their language again.

### Your environment
* f/w version 5.7.0    xAPI version 0.8.3
* all browsers
* all devices + OS

### Steps to reproduce
Create a course
Add a page
Add a text component 
Duplicate the page a few times
Add the xAPI extension and ensure Track state is enabled
Add a few additional languages to the course 
Publish course and add it to platform
Open the course as a learner and select a language
Complete page 1
Exit the course
Re-open the course.

### Expected behaviour
On re-opening, the course should be in the language selected on the previous launch

### Actual behaviour
The language picker screen is presented for users to select their language again

Additional information:
The expected behaviour is currently how it works on a scorm course with spoor enabled.

**Comment by moloko** [comment] 2021-01-11 12:41
duplicate of https://github.com/adaptlearning/adapt-contrib-xapi/issues/88

**Closed by moloko** 2021-01-11 12:41 UTC

**Comment by cahirodoherty-learningpool** [comment] 2021-04-08 08:15
Linked PR: https://github.com/adaptlearning/adapt_framework/pull/3086
