### ISSUE TITLE
when run adapt install get some  Errors

### ISSUE THREAD

**Issue by xdsnet** [adaptlearning/adapt_framework#3554] opened 2024-05-07 01:35 UTC
### Subject of the issue/enhancement/features
when run adapt install get some  Errors

### Your environment
* Framework  5.38.2 ，adapt CLI 3.1.4
* No in brower, On shell run
* debian12 

### Steps to reproduce
in   Framework  dir ,  run
```
adapt install
```

### Expected behaviour
```
adapt_framework# adapt install
installing adapt dependencies...
<info> Getting plugin info 100% complete
<info> Finding compatible source versions 100% complete
<info> Marking installable 100% complete
<info> There is no compatible version of the following plugins:
? adapt-contrib-vanilla master [master]
? adapt-contrib-text master [master]
? adapt-contrib-narrative master [master]
? adapt-contrib-media master [master]
? adapt-contrib-hotgraphic master [master]
? adapt-contrib-blank master [master]
? adapt-contrib-accordion master [master]
? adapt-contrib-graphic master [master]
? adapt-contrib-matching master [master]
? adapt-contrib-textInput master [master]
? adapt-contrib-mcq master [master]
? adapt-contrib-gmcq master [master]
? adapt-contrib-assessment master [master]
? adapt-contrib-assessmentResults master [master]
? adapt-contrib-trickle master [master]
? adapt-contrib-tutor master [master]
? adapt-contrib-boxMenu master [master]
? adapt-contrib-pageLevelProgress master [master]
? adapt-contrib-resources master [master]
? adapt-contrib-slider master [master]
? adapt-contrib-spoor master [master]
? adapt-contrib-bookmarking master [master]
? adapt-contrib-languagePicker master [master]
<info> Installing plugins 4% completeTypeError: Cannot read properties of null (reading 'component')
    at file:///usr/local/lib/node_modules/adapt-cli/lib/integration/Plugin.js:331:62
    at Array.find (<anonymous>)
    at Target.getType (file:///usr/local/lib/node_modules/adapt-cli/lib/integration/Plugin.js:331:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Target.getTypeFolder (file:///usr/local/lib/node_modules/adapt-cli/lib/integration/Plugin.js:342:18)
    at async Target.install (file:///usr/local/lib/node_modules/adapt-cli/lib/integration/Target.js:161:30)
```

### Actual behaviour
Tell us what happens instead

**Comment by swashbuck** [comment] 2024-05-10 20:58
@xdsnet I believe this is a duplicate of https://github.com/adaptlearning/adapt-cli/issues/180

**Comment by oliverfoster** [comment] 2024-05-14 17:44
![image](https://github.com/adaptlearning/adapt_framework/assets/7974663/6684317e-6077-4831-8d06-b52fd6d4abae)

I can't replicate @xdsnet it looks as if your system can't access the registry server.

If you can test access to https://adapt-bower-repository.herokuapp.com/packages/search/adapt-contrib-vanilla and http://adapt-bower-repository.herokuapp.com/packages/search/adapt-contrib-vanilla using curl or similar from your machine, that would help isolate the issue.

**Comment by xdsnet** [comment] 2024-05-15 03:20
It seems that I am unable to access the registration server and both addresses are inaccessible. Is there any other way to obtain registration information? For example, using GitHub to implement registration services?

**Comment by oliverfoster** [comment] 2024-05-15 08:26
You can setup your own registry server. https://github.com/adaptlearning/adapt-registry-server
Or you can proxy to our server.
Or you can figure out why you can't access those urls and allow them.

[Issue closed as external infrastructure problem]

**Closed by oliverfoster** 2024-05-15 08:26 UTC
Labels: bug
