### ISSUE TITLE
IE compatibility in Adapt V4

### ISSUE THREAD

**Issue by michiem** [adaptlearning/adapt_framework#2495] opened 2019-08-06 08:36 UTC
Since Adapt v4 is not working in compatibility view, can we put some pop up or alert for the learner for them to know thay the course will not work in compatibility view?

Also, I tried to use the adapt-IE-check plugin and it is not working when in compatibility view.

**Comment by moloko** [comment] 2019-08-12 11:06
duplicate of https://github.com/cgkineo/adapt-IE-Check/issues/2

**Closed by moloko** 2019-08-12 11:06 UTC
