### ISSUE TITLE
adapt-contrib-bookmarking interprets menu items as pages

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#2729] opened 2020-04-23 15:26 UTC
### Subject of the issue
The plugin checks for the presence of elements bearing a class with a name that matches the bookmarked location. On menus that uses [MenuItemView](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/notifyView.js) this can be a problem: for example if the bookmarked location is `co-100` and one of the menu items has the class `co-100` then the plugin will assume (if the menu item is fully visible) that prompting the user to return to the bookmark is not necessary. The dialog is therefore not shown.

### Your environment
* Adapt v5
* all browsers
* all systems

### Steps to reproduce
Set up a course with adapt-contrib-boxMenu and adapt-contrib-bookmarking and enable bookmarking at page level. Navigate to a page, close the course and reopen. If the menu item corresponding to the bookmarked page is fully visible the return to bookmark prompt is not shown.

### Expected behaviour
The return to bookmark prompt should be shown.

### Actual behaviour
See "Steps to reproduce"

**Comment by danielghost** [comment] 2020-04-27 08:43
Duplicate of https://github.com/adaptlearning/adapt_framework/issues/2659.

**Closed** 2020-04-27 11:00 UTC
Labels: bug, duplicate
